/**
 * Let the release build talk to a plain-http:// backend — narrowly, to
 * exactly the configured host, never as a blanket allowance.
 *
 * Android has blocked cleartext (non-HTTPS) traffic by default since API 28,
 * and this app targets 36. The RN/Expo template papers over this for the
 * **debug** build only — `android/app/src/debug/AndroidManifest.xml` sets
 * `usesCleartextTraffic="true"` unconditionally — which is exactly why
 * Phase 10a's "verified end-to-end" testing, always against a debug build,
 * never caught that the release variant cannot reach anything over `http://`
 * at all. It fails silently from the app's point of view: no exception, no
 * log — `fetch()` simply rejects, which src/lib/api.ts already correctly
 * reports as "could not reach the backend" (see NetworkError there), but
 * with no signal that the actual cause is a platform policy, not a bad URL.
 * This was found by installing a real release build and watching it fail.
 *
 * The fix is a Network Security Config
 * (developer.android.com/training/articles/security-config) that permits
 * cleartext for exactly `EXPO_PUBLIC_API_URL`'s hostname — not
 * `usesCleartextTraffic="true"` app-wide, which would silently accept
 * plaintext to *any* host the app ever talks to, forever, regardless of what
 * `EXPO_PUBLIC_API_URL` says. A `https://` URL (the "Deployed" row in
 * mobile/README.md's table) needs no exception at all and gets none: Android's
 * default — cleartext blocked everywhere except the domains listed here — is
 * the correct, secure behavior for that case, and this plugin leaves it alone.
 */

const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins")
const path = require("node:path")
const fs = require("node:fs")

const DEFAULT_API_URL = "http://10.0.2.2:8000" // must match src/config.ts's own default

/**
 * The hostname to exempt, or null if none is needed.
 *
 * Pure, so the URL-parsing edge cases are testable without touching a real
 * Android project. Returns null for https:// (no exception needed) and for
 * anything unparseable (fail closed — an app that cannot reach an
 * unparseable URL anyway gains nothing from a cleartext exception for it).
 */
function cleartextHostFor(apiUrl) {
  const raw = apiUrl || DEFAULT_API_URL
  let parsed
  try {
    parsed = new URL(raw)
  } catch {
    return null
  }
  return parsed.protocol === "http:" ? parsed.hostname : null
}

function buildNetworkSecurityConfigXml(host) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDevBackendCleartext.js from EXPO_PUBLIC_API_URL.
     Permits plaintext HTTP to exactly this host — never a blanket allowance —
     because the configured backend does not have a TLS certificate. A
     "Deployed" https:// backend needs no entry here and gets none. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">${host}</domain>
    </domain-config>
</network-security-config>
`
}

module.exports = function withDevBackendCleartext(config) {
  const host = cleartextHostFor(process.env.EXPO_PUBLIC_API_URL)
  if (!host) return config

  config = withDangerousMod(config, [
    "android",
    (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, "app/src/main/res/xml")
      fs.mkdirSync(xmlDir, { recursive: true })
      fs.writeFileSync(
        path.join(xmlDir, "network_security_config.xml"),
        buildNetworkSecurityConfigXml(host),
      )
      return cfg
    },
  ])

  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0]
    if (!application) {
      throw new Error(
        "withDevBackendCleartext: no <application> element in the merged manifest. " +
          "The Expo template changed; update this plugin rather than shipping a " +
          "release build that cannot reach its own configured backend.",
      )
    }
    application.$["android:networkSecurityConfig"] = "@xml/network_security_config"
    return cfg
  })
}

module.exports.cleartextHostFor = cleartextHostFor
module.exports.buildNetworkSecurityConfigXml = buildNetworkSecurityConfigXml
