/**
 * Let the release build talk to a plain-http:// backend — narrowly, to
 * exactly the configured host, never as a blanket allowance.
 *
 * Android has blocked cleartext (non-HTTPS) traffic by default since API 28,
 * and this app targets 36. The RN/Expo template papers over this for the
 * **debug** build only — `android/app/src/debug/AndroidManifest.xml` sets
 * `usesCleartextTraffic="true"` unconditionally — which is exactly why
 * Phase 10a's "verified end-to-end" testing, always against a debug build,
 * never caught that the release variant cannot reach anything over `http://`
 * at all. It fails silently from the app's point of view: no exception, no
 * log — `fetch()` simply rejects, which src/lib/api.ts already correctly
 * reports as "could not reach the backend" (see NetworkError there), but
 * with no signal that the actual cause is a platform policy, not a bad URL.
 * This was found by installing a real release build and watching it fail.
 *
 * The fix is a Network Security Config
 * (developer.android.com/training/articles/security-config) that permits
 * cleartext for exactly `EXPO_PUBLIC_API_URL`'s hostname — not
 * `usesCleartextTraffic="true"` app-wide, which would silently accept
 * plaintext to *any* host the app ever talks to, forever, regardless of what
 * `EXPO_PUBLIC_API_URL` says. A `https://` URL (the "Deployed" row in
 * mobile/README.md's table) needs no exception at all and gets none: Android's
 * default — cleartext blocked everywhere except the domains listed here — is
 * the correct, secure behavior for that case, and this plugin leaves it alone.
 *
 * One asymmetry, and it is load-bearing: the narrow config goes in
 * `src/main/res`, which every variant inherits — *including debug*. A
 * networkSecurityConfig takes precedence over `usesCleartextTraffic`, so
 * pointing the main manifest at an allow-list silently revoked the blanket
 * permission the template had given the debug build, and the dev client could
 * no longer reach Metro: `expo run:android` serves the bundle from the
 * machine's LAN address, which is not the backend host and so is not on the
 * list. The app died on launch with UnknownServiceException rather than
 * anything mentioning this plugin. Found by running `make mobile-android`
 * after a prebuild — the previous pass asserted the dev loop was unaffected
 * without re-running it.
 *
 * The fix is a second config in `src/debug/res`, which Android's variant
 * merging prefers over `src/main/res` for that variant only. Debug keeps
 * exactly the posture the template already gave it (cleartext anywhere — it is
 * a build that talks to a developer's laptop by IP), and release keeps the
 * allow-list, which is the variant the narrowness was ever for.
 */

const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins")
const path = require("node:path")
const fs = require("node:fs")

const DEFAULT_API_URL = "http://10.0.2.2:8000" // must match src/config.ts's own default

/**
 * The hostname to exempt, or null if none is needed.
 *
 * Pure, so the URL-parsing edge cases are testable without touching a real
 * Android project. Returns null for https:// (no exception needed) and for
 * anything unparseable (fail closed — an app that cannot reach an
 * unparseable URL anyway gains nothing from a cleartext exception for it).
 */
function cleartextHostFor(apiUrl) {
  const raw = apiUrl || DEFAULT_API_URL
  let parsed
  try {
    parsed = new URL(raw)
  } catch {
    return null
  }
  return parsed.protocol === "http:" ? parsed.hostname : null
}

/**
 * The debug variant's config: cleartext to anything.
 *
 * Not a weakening of the release policy — it is the policy the RN template's
 * `android/app/src/debug/AndroidManifest.xml` already set with
 * `usesCleartextTraffic="true"`, restated in the form that actually wins.
 * A debug build talks to Metro and a backend on a developer's LAN by raw IP,
 * neither of which is knowable at prebuild time.
 */
function buildDebugNetworkSecurityConfigXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDevBackendCleartext.js — DEBUG VARIANT ONLY.
     Android prefers src/debug/res over src/main/res for this build type, so
     the release allow-list next door is untouched. This restores the blanket
     cleartext permission the RN template's debug manifest already granted,
     which a networkSecurityConfig on the main manifest otherwise overrides —
     taking Metro's own LAN address down with it. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`
}

function buildNetworkSecurityConfigXml(host) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDevBackendCleartext.js from EXPO_PUBLIC_API_URL.
     Permits plaintext HTTP to exactly this host — never a blanket allowance —
     because the configured backend does not have a TLS certificate. A
     "Deployed" https:// backend needs no entry here and gets none. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">${host}</domain>
    </domain-config>
</network-security-config>
`
}

module.exports = function withDevBackendCleartext(config) {
  const host = cleartextHostFor(process.env.EXPO_PUBLIC_API_URL)
  if (!host) return config

  config = withDangerousMod(config, [
    "android",
    (cfg) => {
      const write = (variant, xml) => {
        const xmlDir = path.join(
          cfg.modRequest.platformProjectRoot,
          `app/src/${variant}/res/xml`,
        )
        fs.mkdirSync(xmlDir, { recursive: true })
        fs.writeFileSync(path.join(xmlDir, "network_security_config.xml"), xml)
      }

      write("main", buildNetworkSecurityConfigXml(host))
      // Same resource name on purpose: that is what makes the variant override
      // work. Debug resolves to this one, release to the allow-list above.
      write("debug", buildDebugNetworkSecurityConfigXml())
      return cfg
    },
  ])

  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0]
    if (!application) {
      throw new Error(
        "withDevBackendCleartext: no <application> element in the merged manifest. " +
          "The Expo template changed; update this plugin rather than shipping a " +
          "release build that cannot reach its own configured backend.",
      )
    }
    application.$["android:networkSecurityConfig"] = "@xml/network_security_config"
    return cfg
  })
}

module.exports.cleartextHostFor = cleartextHostFor
module.exports.buildNetworkSecurityConfigXml = buildNetworkSecurityConfigXml
module.exports.buildDebugNetworkSecurityConfigXml = buildDebugNetworkSecurityConfigXml
