"""Turns a SignalBundle into plain-English incident text, deterministically,
with no model and no network call.

This replaces the Phase 8 pair app/ai/prompts.py + app/ai/client.py, which
sent the bundle to Haiku and Sonnet. The contract it keeps is CLAUDE.md's
original one, only harder: the explainer still never detects. Where the LLM
version *promised* not to invent a detection, this version cannot — every
sentence below is a formatting of a value app/analysis/ already computed,
and there is no branch that can emit a claim the bundle does not contain.

That also retires the `<incident_data>` prompt boundary rather than
weakening it. A device or rule name is still free text its owner chose, but
nothing here interprets a string: names are interpolated into output and
never read as instructions, so the injection surface the old system prompt
had to argue its way out of does not exist.

Two rules govern every template here:

* A field that is None produces no clause, never a zeroed or hedged one.
  Same posture as analysis/health.py excluding an unreported component
  rather than scoring it 0 — a sentence about a measurement nobody took is
  the prose form of a synthesised metric. A thin bundle yields fewer
  sentences, never vaguer ones.
* Nothing here reads a value to make a decision that flows back into the
  system. The output is inert display text, exactly as it was when Claude
  wrote it (see app/models/incidents.py).

Every function is pure and takes `now` explicitly rather than reading the
clock, the same testability posture as analysis/alerts.py's step() and
analysis/report_schedule.py's is_due().
"""

from __future__ import annotations

from datetime import datetime

from app.analysis.anomaly import classify_severity
from app.services.signal_bundle import (
    EventSnapshot,
    ExhaustionSnapshot,
    ForecastSnapshot,
    SignalBundle,
)

#: Written to Incident.summary_model / root_cause_model where a model id used
#: to go. That column keeps meaning exactly what it meant — "what produced
#: this text" — so rows generated by Haiku/Sonnet before the switch stay
#: distinguishable from these, and a template change that alters wording can
#: bump the version rather than silently rewriting history.
GENERATOR_ID = "sentinel-templates/v1"

#: Metric key -> (human label, unit).
#:
#: Kept as its own table rather than imported from analysis/health.py's _SPEC
#: because the two vocabularies genuinely differ by one name: the health
#: component reads `memory_percent` off its inputs, while the alert metric —
#: the thing an AlertEvent actually carries — is `mem_percent`. Importing
#: would need a translation layer for a six-row table.
_METRICS: dict[str, tuple[str, str]] = {
    "cpu_percent": ("CPU", "%"),
    "mem_percent": ("memory", "%"),
    "disk_percent": ("disk usage", "%"),
    "swap_percent": ("swap", "%"),
    "packet_loss_percent": ("packet loss", "%"),
    "cpu_iowait_percent": ("IO wait", "%"),
    # Layer 4's reserved metric. It is a percentile, not a percentage of
    # anything, so it carries no unit — "novelty 95%" would read as though 95%
    # of something were unusual.
    "novelty_score": ("the overall pattern", ""),
}

#: Which of several simultaneous alerts is the headline. Follows
#: analysis/health.py's own component weights (disk 4 > cpu/memory 3 >
#: network 2 > swap/iowait 1) so "which of these events leads the sentence"
#: cannot disagree with "which of these dragged the health score down".
_RANK: dict[str, int] = {
    "disk_percent": 4,
    "cpu_percent": 3,
    "mem_percent": 3,
    "packet_loss_percent": 2,
    "swap_percent": 1,
    "cpu_iowait_percent": 1,
    # Below disk/CPU/memory on purpose: a combination alert says something is
    # unusual, while those say something is *running out*. When both fire, the
    # actionable one should lead the sentence.
    "novelty_score": 2,
}

#: Below this, a forecast's start-to-end movement is described as flat rather
#: than as a rise or fall — a 0.3-point drift over 24h is noise, and naming a
#: direction for it would read as a trend the fit does not support.
FLAT_FORECAST_DELTA = 1.0

#: A health component scoring below this is worth naming as a contributor.
#: Matches analysis/health.py's DEGRADED_AT band edge.
DRAGGING_BELOW = 70


def label_for(metric: str) -> str:
    return _METRICS.get(metric, (metric, ""))[0]


def _fmt(metric: str, value: float | None) -> str | None:
    """None in, None out — the caller drops its clause rather than printing
    "unknown". A reading that does not exist has no sentence."""
    if value is None:
        return None
    unit = _METRICS.get(metric, ("", ""))[1]
    return f"{value:.1f}{unit}"


def _duration(seconds: float) -> str:
    seconds = max(seconds, 0)
    if seconds < 90:
        return f"{int(seconds)}s"
    if seconds < 5400:
        return f"{int(seconds // 60)}m"
    if seconds < 172800:
        return f"{seconds / 3600:.1f}h"
    return f"{seconds / 86400:.1f} days"


def _join(parts: list[str]) -> str:
    if len(parts) == 1:
        return parts[0]
    return f"{', '.join(parts[:-1])} and {parts[-1]}"


# --------------------------------------------------------------------------
# One event, in words.
#
# This is app/alerts/notify.py's _condition() applied to an EventSnapshot
# instead of an AlertEvent — the same four-way branch on rule_type, and the
# same refusal to read comparison/threshold for an anomaly event, which is
# the bug that put a literal "(None None)" into every anomaly notification.
#
# Adding the multivariate branch meant editing both copies, which is the cost
# of the duplication finally showing up. Still two callers, so still not worth
# a shared helper over a Protocol — but a third would settle it.
# --------------------------------------------------------------------------


def _condition(event: EventSnapshot, now: datetime) -> str:
    if event.rule_type == "anomaly":
        if event.baseline_mean is None or event.z_score is None:
            return "reading unusually for this device"
        normal = _fmt(event.metric, event.baseline_mean)
        if normal is None:
            return f"running {event.z_score:+.1f} sigma from its usual range"
        return f"running {event.z_score:+.1f} sigma from its usual {normal}"

    if event.rule_type == "multivariate":
        # Not a measurement, so the raw "> 71.0" the threshold branch would
        # produce is meaningless here: the number is a percentile against this
        # machine's own history, and saying so is the difference between "71"
        # and "71% of something".
        if event.threshold is None:
            return "showing an unusual combination of readings"
        return f"scoring above {event.threshold:.0f}/100 for unusualness"

    target = _fmt(event.metric, event.threshold)
    if event.rule_type == "forecast":
        clause = f"forecast to go {event.comparison} {target}" if target else "forecast to breach"
        if event.predicted_breach_at is not None:
            ahead = (event.predicted_breach_at - now).total_seconds()
            clause += f" in about {_duration(ahead)}"
        return clause

    return f"{event.comparison} {target}" if target else "past its threshold"


def _severity_rank(event: EventSnapshot) -> tuple[int, int, float]:
    """Firing outranks resolved; then the metric's own health weight; then,
    within a tie, how far out the anomaly was. Total order on every field, so
    the same bundle always produces the same headline."""
    firing = 0 if event.status == "firing" else 1
    magnitude = abs(event.z_score) if event.z_score is not None else 0.0
    return (firing, -_RANK.get(event.metric, 0), -magnitude)


def _lead_event(bundle: SignalBundle) -> EventSnapshot | None:
    if not bundle.events:
        return None
    return sorted(bundle.events, key=_severity_rank)[0]


# --------------------------------------------------------------------------
# Summary — one sentence, the notification-banner slot Haiku used to fill.
# --------------------------------------------------------------------------


def summarize(bundle: SignalBundle, *, now: datetime) -> str:
    device = bundle.device.name
    lead = _lead_event(bundle)
    if lead is None:
        # Reachable only if every event was detached from the incident. Say
        # so rather than describing an incident with no evidence in it.
        return f"Incident on {device} with no correlated alerts recorded."

    others = len(bundle.events) - 1
    also = f" and {others} other alert{'s' if others > 1 else ''}" if others else ""
    metric = label_for(lead.metric)
    condition = _condition(lead, now)

    if bundle.incident_status == "resolved":
        span = _duration(((bundle.closed_at or now) - bundle.opened_at).total_seconds())
        return f"Resolved after {span}: {metric} on {device} was {condition}{also}."

    current = lead.last_value if lead.last_value is not None else lead.value_at_fire
    reading = _fmt(lead.metric, current)
    seen = f" (now {reading})" if reading else ""
    return f"{metric} on {device} is {condition}{seen}{also}."


# --------------------------------------------------------------------------
# Root cause — the 3-6 sentence slot Sonnet used to fill.
#
# Built as a list of optional clauses. There is no "the evidence is too thin
# to point to a cause" fallback sentence, which the LLM prompt needed: a thin
# bundle simply contributes fewer clauses, so the output shortens instead of
# hedging.
# --------------------------------------------------------------------------


def _opening_sentence(bundle: SignalBundle, lead: EventSnapshot, now: datetime) -> str:
    return (
        f"{bundle.device.name} opened an incident when {label_for(lead.metric)} went "
        f"{_condition(lead, now)}, at {lead.fired_at:%H:%M UTC on %d %b}."
    )


def _correlation_sentence(bundle: SignalBundle, now: datetime) -> str | None:
    """Why these alerts are one incident rather than several. Only says
    anything when there is actually a correlation to explain."""
    if len(bundle.events) < 2:
        return None
    metrics = _join(sorted({label_for(e.metric) for e in bundle.events}))
    window = max(e.fired_at for e in bundle.events) - min(e.fired_at for e in bundle.events)
    detail = (
        f" within {_duration(window.total_seconds())} of each other"
        if window.total_seconds() > 0
        else " at the same moment"
    )
    # Name the kinds actually present rather than reciting a fixed list. The
    # hardcoded "threshold, anomaly and forecast" predated the multivariate
    # rule type and started describing the wrong set the moment it landed —
    # the same way notify.py's threshold-shaped body did when anomaly rules
    # arrived.
    kinds = sorted({e.rule_type for e in bundle.events})
    how = f" across {_join(kinds)} rules" if len(kinds) > 1 else ""
    return f"{metrics} alerted{detail}{how}, which is why they correlated into one incident."


def _baseline_sentence(bundle: SignalBundle) -> str | None:
    """What "normal" actually was — the number that makes an anomaly event
    meaningful rather than just a sigma count.

    Uses the event's *snapshotted* baseline, never the live AnomalyBaseline
    row, for the same reason AnomalyEvidenceChart draws the two as separate
    lines (Phase 6): the live one has drifted since, and presenting it as
    "normal at the time" would be false.
    """
    anomalies = [e for e in bundle.events if e.rule_type == "anomaly" and e.z_score is not None]
    if not anomalies:
        return None
    worst = max(anomalies, key=lambda e: abs(e.z_score or 0.0))
    z = worst.z_score or 0.0
    observed = _fmt(worst.metric, worst.observed_value or worst.value_at_fire)
    normal = _fmt(worst.metric, worst.baseline_mean)
    if observed is None or normal is None:
        return None
    direction = "above" if z > 0 else "below"
    return (
        f"The adaptive baseline rates this {classify_severity(z)}: "
        f"{label_for(worst.metric)} sat at {normal} before the incident and read "
        f"{observed}, {abs(z):.1f} sigma {direction} that."
    )


def _health_sentence(bundle: SignalBundle) -> str:
    health = bundle.health
    if health.score is None:
        reason = health.reason or "no recent readings"
        return f"The device's health score is unavailable ({reason})."

    sentence = f"Health is {health.score}/100 ({health.band})"
    dragging = sorted(
        (
            c
            for c in health.components
            if c.get("score") is not None and c["score"] < DRAGGING_BELOW
        ),
        key=lambda c: (c["score"], -c["weight"]),
    )
    if dragging:
        worst = dragging[0]
        sentence += (
            f", pulled down mainly by {worst['label'].lower()} at "
            f"{worst['value']:.1f}{worst['unit']}"
        )
    sentence += "."

    # Never let a shorter explanation read as a broken agent — the same
    # reasoning docs/ANDROID_METRICS.md forces onto the device screens. Uses
    # the component *key*, matching the "Not measurable on this platform:
    # cpu, iowait" wording both frontends already show.
    unavailable = [c["key"] for c in health.components if c.get("value") is None]
    if unavailable:
        sentence += f" Not measurable on this platform: {', '.join(unavailable)}."
    return sentence


def _trajectory_sentence(
    forecasts: tuple[ForecastSnapshot, ...],
    exhaustion: tuple[ExhaustionSnapshot, ...],
    now: datetime,
) -> str | None:
    """Where this is heading — but only for a metric with a real projection.

    A forecast row whose fit was empty carries None for its predicted points
    and is skipped: that row exists to record that the check ran, not to
    assert a trend (Phase 7's MIN_POINTS_TREND posture).

    A projection whose date has already passed is skipped for the same
    reason. Found against the real database: a device removed days ago still
    carried an exhaustion row projecting +237.6 points/day, and describing it
    rendered as "reaches capacity in about 0s" — a claim about a future that
    has been overtaken. Nothing recomputes a stored forecast once its device
    stops reporting, so "still ahead of now" is the only thing that makes it
    a forecast rather than a fossil.
    """
    dated = [(e.projected_at, e) for e in exhaustion if e.projected_at is not None]
    dated = [pair for pair in dated if pair[0] > now]
    if dated:
        projected_at, worst = min(dated, key=lambda pair: pair[0])
        where = f" on {worst.entity}" if worst.entity else ""
        ahead = _duration((projected_at - now).total_seconds())
        return (
            f"At the current rate ({worst.slope_per_day:+.1f} points/day), "
            f"{label_for(worst.metric)}{where} reaches capacity in about {ahead}."
        )

    trending = [
        f for f in forecasts if f.first_predicted is not None and f.last_predicted is not None
    ]
    if not trending:
        return None
    worst = max(trending, key=lambda f: abs((f.last_predicted or 0.0) - (f.first_predicted or 0.0)))
    delta = (worst.last_predicted or 0.0) - (worst.first_predicted or 0.0)
    horizon = _duration(worst.horizon_seconds)
    if abs(delta) < FLAT_FORECAST_DELTA:
        return (
            f"{label_for(worst.metric)} is forecast to stay roughly flat over the next {horizon}."
        )
    verb = "rise" if delta > 0 else "fall"
    end = _fmt(worst.metric, worst.last_predicted)
    return f"{label_for(worst.metric)} is forecast to {verb} to {end} over the next {horizon}."


def _next_step_sentence(bundle: SignalBundle, now: datetime) -> str | None:
    """A recommendation only where the data names its own object — a specific
    mount that is filling, a specific target losing packets.

    Anything vaguer would be advice the bundle does not support, which is the
    one thing the old prompt had to ask the model not to do and the one thing
    a template can actually guarantee. Advice from an expired projection is
    the same problem in a costlier form — it sends somebody to a disk — so
    the future-dated filter from _trajectory_sentence applies here too.
    """
    filling = [
        (e.projected_at, e)
        for e in bundle.exhaustion
        if e.projected_at is not None
        and e.projected_at > now
        and e.entity
        and e.metric == "disk_percent"
    ]
    if filling:
        _, worst = min(filling, key=lambda pair: pair[0])
        return f"Next step: free space on {worst.entity}, currently {worst.current_value:.1f}%."

    lossy = any(e.metric == "packet_loss_percent" and e.status == "firing" for e in bundle.events)
    if lossy:
        return (
            "Next step: check the network path to the affected target before "
            "treating this as a host problem."
        )
    return None


def explain(bundle: SignalBundle, *, now: datetime) -> str:
    lead = _lead_event(bundle)
    if lead is None:
        return (
            "This incident has no correlated alert events recorded, so there is nothing to analyse."
        )
    sentences = [
        _opening_sentence(bundle, lead, now),
        _correlation_sentence(bundle, now),
        _baseline_sentence(bundle),
        _health_sentence(bundle),
        _trajectory_sentence(bundle.forecasts, bundle.exhaustion, now),
        _next_step_sentence(bundle, now),
    ]
    return " ".join(s for s in sentences if s)


class TemplateInsightGenerator:
    """The default InsightGenerator (app/insights/service.py's Protocol).

    A class wrapping two pure functions, for one reason: it preserves the
    substitution seam app/ai/client.py's AIClient had, so a locally-hosted
    model could be dropped in later without touching the service, the worker
    or the route. It holds no state and needs no configuration — unlike the
    client it replaces, constructing one cannot fail.
    """

    def summarize(self, bundle: SignalBundle, *, now: datetime) -> str:
        return summarize(bundle, now=now)

    def explain(self, bundle: SignalBundle, *, now: datetime) -> str:
        return explain(bundle, now=now)
