"""The agent↔backend WebSocket protocol.

One schema, imported by both sides, so the agent cannot drift from the server.

Design notes:

* The agent connects **outbound** only. No inbound ports, works behind NAT and
  corporate firewalls.
* Every message is a JSON object with a `type` discriminator. Frames are
  size-capped and schema-validated before anything touches the database — an
  agent token is a long-lived credential on a machine we do not control, so its
  payloads are treated as untrusted input.
* Timestamps are ISO-8601 UTC, generated by the agent. The server records its
  own receive time separately and rejects samples too far outside its clock.
* Missing metrics are `null`, never zero and never omitted-and-defaulted. A
  platform that cannot measure something reports nothing for it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

PROTOCOL_VERSION = 1

#: Hard cap on a single WebSocket frame. A 10s batch of one device is a few KB;
#: 512 KiB is generous for a slow agent catching up after a reconnect and still
#: small enough that a malicious agent cannot exhaust memory with one frame.
MAX_FRAME_BYTES = 512 * 1024

#: Samples older or newer than this relative to server time are rejected. Agents
#: buffer across reconnects, so the past window is deliberately wide; the future
#: window is tight because a future timestamp is either a broken clock or an
#: attempt to poison a forecast.
MAX_SAMPLE_AGE_SECONDS = 60 * 60
MAX_SAMPLE_SKEW_SECONDS = 120

#: Per-message limits, enforced by Pydantic before any database work.
MAX_SAMPLES_PER_BATCH = 240
MAX_ENTITIES_PER_SAMPLE = 64
MAX_PROCESSES_PER_SAMPLE = 20


class _Frame(BaseModel):
    model_config = ConfigDict(extra="forbid")


# --- host metadata ----------------------------------------------------------


class HostInfo(_Frame):
    """Reported once at connect. Updates the device row."""

    hostname: str = Field(max_length=255)
    os: str = Field(max_length=64)
    os_version: str | None = Field(default=None, max_length=128)
    kernel_version: str | None = Field(default=None, max_length=128)
    arch: str | None = Field(default=None, max_length=32)
    cpu_cores: int | None = Field(default=None, ge=1, le=4096)
    total_memory_bytes: int | None = Field(default=None, ge=0)
    agent_version: str = Field(max_length=32)
    platform: Literal["desktop", "android"] = "desktop"


# --- sample payloads --------------------------------------------------------

Percent = Annotated[float, Field(ge=0, le=100)]
NonNegative = Annotated[float, Field(ge=0)]


class SystemSample(_Frame):
    cpu_percent: Percent | None = None
    cpu_percent_min: Percent | None = None
    cpu_percent_max: Percent | None = None
    cpu_user_percent: Percent | None = None
    cpu_system_percent: Percent | None = None
    cpu_iowait_percent: Percent | None = None
    cpu_freq_mhz: NonNegative | None = None
    ctx_switches_per_s: NonNegative | None = None
    load1: NonNegative | None = None
    load5: NonNegative | None = None
    load15: NonNegative | None = None

    mem_total_bytes: int | None = Field(default=None, ge=0)
    mem_used_bytes: int | None = Field(default=None, ge=0)
    mem_available_bytes: int | None = Field(default=None, ge=0)
    mem_percent: Percent | None = None
    mem_percent_min: Percent | None = None
    mem_percent_max: Percent | None = None
    swap_total_bytes: int | None = Field(default=None, ge=0)
    swap_used_bytes: int | None = Field(default=None, ge=0)
    swap_percent: Percent | None = None

    uptime_seconds: int | None = Field(default=None, ge=0)
    logged_in_users: int | None = Field(default=None, ge=0, le=32767)
    process_count: int | None = Field(default=None, ge=0)
    active_connections: int | None = Field(default=None, ge=0)
    temperature_celsius: float | None = Field(default=None, ge=-273.15, le=500)
    fan_rpm: NonNegative | None = None
    battery_percent: Percent | None = None
    battery_plugged: bool | None = None


class DiskUsageEntry(_Frame):
    mount: str = Field(max_length=255)
    filesystem: str | None = Field(default=None, max_length=64)
    total_bytes: int | None = Field(default=None, ge=0)
    used_bytes: int | None = Field(default=None, ge=0)
    free_bytes: int | None = Field(default=None, ge=0)
    percent: Percent | None = None


class DiskIoEntry(_Frame):
    disk: str = Field(max_length=255)
    read_bytes_per_s: NonNegative | None = None
    write_bytes_per_s: NonNegative | None = None
    read_iops: NonNegative | None = None
    write_iops: NonNegative | None = None
    busy_percent: Percent | None = None


class NetEntry(_Frame):
    nic: str = Field(max_length=255)
    tx_bytes_per_s: NonNegative | None = None
    rx_bytes_per_s: NonNegative | None = None
    tx_packets_per_s: NonNegative | None = None
    rx_packets_per_s: NonNegative | None = None
    errors_in_per_s: NonNegative | None = None
    errors_out_per_s: NonNegative | None = None
    drops_in_per_s: NonNegative | None = None
    drops_out_per_s: NonNegative | None = None


class LatencyEntry(_Frame):
    target: str = Field(max_length=255)
    reachable: bool
    rtt_ms_avg: NonNegative | None = None
    rtt_ms_min: NonNegative | None = None
    rtt_ms_max: NonNegative | None = None
    packet_loss_percent: Percent | None = None


class ProcessEntry(_Frame):
    rank_by: Literal["cpu", "memory"]
    rank: int = Field(ge=1, le=MAX_PROCESSES_PER_SAMPLE)
    pid: int = Field(ge=0)
    name: str = Field(max_length=255)
    username: str | None = Field(default=None, max_length=255)
    cpu_percent: float | None = Field(default=None, ge=0)
    memory_bytes: int | None = Field(default=None, ge=0)


class Sample(_Frame):
    """One point in time for one device."""

    ts: datetime
    resolution_seconds: Literal[1, 10]
    system: SystemSample
    disk_usage: list[DiskUsageEntry] = Field(
        default_factory=list, max_length=MAX_ENTITIES_PER_SAMPLE
    )
    disk_io: list[DiskIoEntry] = Field(default_factory=list, max_length=MAX_ENTITIES_PER_SAMPLE)
    net: list[NetEntry] = Field(default_factory=list, max_length=MAX_ENTITIES_PER_SAMPLE)
    latency: list[LatencyEntry] = Field(
        default_factory=list, max_length=MAX_ENTITIES_PER_SAMPLE
    )
    processes: list[ProcessEntry] = Field(
        default_factory=list, max_length=MAX_PROCESSES_PER_SAMPLE * 2
    )


# --- frames: agent → server -------------------------------------------------


class HelloFrame(_Frame):
    type: Literal["hello"] = "hello"
    protocol_version: int
    host: HostInfo


class MetricsFrame(_Frame):
    type: Literal["metrics"] = "metrics"
    #: Echoed back in the ack so the agent knows what it may drop from its buffer.
    batch_id: str = Field(max_length=64)
    samples: list[Sample] = Field(min_length=1, max_length=MAX_SAMPLES_PER_BATCH)


class PongFrame(_Frame):
    type: Literal["pong"] = "pong"


AgentFrame = Annotated[
    HelloFrame | MetricsFrame | PongFrame,
    Field(discriminator="type"),
]


# --- frames: server → agent -------------------------------------------------


class WelcomeFrame(_Frame):
    type: Literal["welcome"] = "welcome"
    device_id: str
    #: Echoed so an agent built against a newer protocol can refuse to continue.
    protocol_version: int = PROTOCOL_VERSION
    #: The push cadence the agent should use right now.
    mode: Literal["normal", "live"] = "normal"
    push_interval_seconds: int


class AckFrame(_Frame):
    type: Literal["ack"] = "ack"
    batch_id: str
    accepted: int
    #: Samples dropped for being outside the accepted time window. The agent
    #: logs these rather than retrying — retrying would never succeed.
    rejected: int = 0


class ModeFrame(_Frame):
    """Sent when a viewer opens Live Monitoring, and again when they leave."""

    type: Literal["mode"] = "mode"
    mode: Literal["normal", "live"]
    push_interval_seconds: int


class PingFrame(_Frame):
    type: Literal["ping"] = "ping"


class ErrorFrame(_Frame):
    type: Literal["error"] = "error"
    code: Literal[
        "unauthorized", "protocol_version", "invalid_frame", "too_large", "rate_limited"
    ]
    message: str
    #: False means the agent should stop retrying — reconnecting will not help.
    retryable: bool = True


ServerFrame = WelcomeFrame | AckFrame | ModeFrame | PingFrame | ErrorFrame
