/**
 * One incident: its correlated-alert timeline, the AI summary (Haiku) and the
 * root-cause analysis (Sonnet). The phone counterpart of
 * web/src/pages/IncidentDetailPage.tsx.
 *
 * The list screen deliberately showed only the summary sentence, because
 * `GET /incidents` returns `Incident` and not `IncidentDetail` — fetching the
 * timeline for every row would be one request per incident. This screen is
 * that second request, made once, for the incident you actually opened.
 *
 * Both texts are rendered as inert display text and nothing here parses either
 * back into structure. That is CLAUDE.md's "the LLM explains; it does not
 * detect" at the render layer: the phone shows the sentence, and the state
 * machine that opened the incident is unaffected by what it says.
 */

import { useEffect, useState } from "react"
import { StyleSheet, Text, View } from "react-native"

import { AlertStatusBadge } from "@/components/Badges"
import { Screen } from "@/components/Screen"
import { Button, Card, CardTitle, ErrorNote } from "@/components/ui"
import { ApiError, apiFetch } from "@/lib/api"
import { DEVICE_LIST_WITH_REMOVED, deviceLabel, indexDevices } from "@/lib/deviceNames"
import { formatRelative } from "@/lib/timeRanges"
import { colors, spacing, text } from "@/theme"
import type { Device } from "@/types/api"
import type { IncidentDetail } from "@/types/incidents"
import type { RootStackScreenProps } from "@/navigation/types"

export function IncidentDetailScreen({ route }: RootStackScreenProps<"IncidentDetail">) {
  const { incidentId } = route.params
  const [incident, setIncident] = useState<IncidentDetail | null>(null)
  const [devices, setDevices] = useState<Record<string, Device>>({})
  const [error, setError] = useState<string | null>(null)
  const [regenerating, setRegenerating] = useState(false)
  const [regenerateError, setRegenerateError] = useState<string | null>(null)
  const [refreshing, setRefreshing] = useState(false)

  const load = async (viaGesture = false) => {
    if (viaGesture) setRefreshing(true)
    try {
      setIncident(await apiFetch<IncidentDetail>(`/incidents/${incidentId}`))
      setError(null)
    } catch {
      setError("Could not load this incident.")
    } finally {
      setRefreshing(false)
    }
  }

  useEffect(() => {
    void load()
    // Removed devices included: an incident is history and outlives the
    // machine it happened on. See lib/deviceNames.ts.
    apiFetch<Device[]>(DEVICE_LIST_WITH_REMOVED)
      .then((list) => setDevices(indexDevices(list)))
      .catch(() => {
        // Non-fatal: the header falls back to a short device id.
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [incidentId])

  const regenerate = async () => {
    setRegenerating(true)
    setRegenerateError(null)
    try {
      setIncident(
        await apiFetch<IncidentDetail>(`/incidents/${incidentId}/regenerate`, { method: "POST" }),
      )
    } catch (err) {
      // A 503 here means no ANTHROPIC_API_KEY is configured on the server. The
      // route raises rather than no-opping precisely so somebody who pressed a
      // button learns it did not happen — surfaced, not swallowed.
      setRegenerateError(
        err instanceof ApiError ? err.message : "Could not regenerate insights.",
      )
    } finally {
      setRegenerating(false)
    }
  }

  return (
    <Screen refreshing={refreshing} onRefresh={() => void load(true)}>
      {error && <ErrorNote message={error} />}
      {!incident && !error && <Text style={text.small}>Loading…</Text>}

      {incident && (
        <>
          <Card>
            <View style={styles.head}>
              <Text style={text.title} numberOfLines={1}>
                {deviceLabel(devices, incident.device_id)}
              </Text>
              <AlertStatusBadge status={incident.status === "open" ? "firing" : "resolved"} />
            </View>
            <Text style={text.tiny}>
              opened {formatRelative(incident.opened_at)}
              {incident.closed_at ? ` · closed ${formatRelative(incident.closed_at)}` : ""}
            </Text>
          </Card>

          <Card>
            <CardTitle>Summary</CardTitle>
            <Text style={text.body}>{incident.summary_text ?? "Not generated yet."}</Text>
            <Text style={text.tiny}>
              {incident.summary_model
                ? `Generated by ${incident.summary_model}.`
                : "Generated by Claude Haiku from this incident's evidence."}
            </Text>
          </Card>

          <Card>
            <CardTitle>Root cause analysis</CardTitle>
            <Text style={text.body}>{incident.root_cause_text ?? "Not generated yet."}</Text>
            <Text style={text.tiny}>
              {incident.root_cause_model
                ? `Generated by ${incident.root_cause_model}.`
                : "Generated by Claude Sonnet from this incident's evidence."}
            </Text>
          </Card>

          {regenerateError && <ErrorNote message={regenerateError} />}
          <Button
            variant="outline"
            title="Regenerate insights"
            busy={regenerating}
            onPress={() => void regenerate()}
          />
          <Text style={text.tiny}>
            Costs an API call. The background worker already refreshes these whenever the set of
            correlated alerts changes, so this is only for asking again after nothing did.
          </Text>

          <Card>
            <CardTitle>Timeline</CardTitle>
            {incident.events.length === 0 ? (
              <Text style={text.small}>No events attached.</Text>
            ) : (
              incident.events.map((event) => (
                <View key={event.id} style={styles.event}>
                  <View style={styles.eventHead}>
                    <Text style={text.body} numberOfLines={1}>
                      {event.rule_name}
                    </Text>
                    <AlertStatusBadge status={event.status} />
                  </View>
                  <Text style={text.small}>
                    {event.metric}{" "}
                    {event.rule_type === "anomaly"
                      ? `anomaly (${event.severity ?? "unclassified"})`
                      : `${event.rule_type === "forecast" ? "predicted " : ""}${event.comparison} ${event.threshold}`}
                  </Text>
                  <Text style={text.tiny}>
                    {event.status === "firing"
                      ? `fired ${formatRelative(event.fired_at)}`
                      : `resolved ${formatRelative(event.resolved_at ?? event.fired_at)}`}
                  </Text>
                </View>
              ))
            )}
          </Card>
        </>
      )}
    </Screen>
  )
}

const styles = StyleSheet.create({
  head: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  event: {
    gap: 2,
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  eventHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
})
