"""auth schema: users, refresh_tokens, devices, agent_tokens, enrollment_codes

Table definitions are autogenerated from app/models/. The row-level security
block at the end of upgrade() is hand-written — autogenerate never produces
policies or grants.

Revision ID: 0002_auth_schema
Revises: 0001_bootstrap_roles
Create Date: 2026-08-22 06:18:26.644966+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_auth_schema'
down_revision: Union[str, Sequence[str], None] = '0001_bootstrap_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (table, tenant column). `users` scopes on its own primary key; every other
# table carries a denormalized user_id so the policy is one indexed predicate
# with no join.
TENANT_TABLES = (
    ("users", "id"),
    ("devices", "user_id"),
    ("refresh_tokens", "user_id"),
    ("agent_tokens", "user_id"),
    ("enrollment_codes", "user_id"),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('os', sa.Text(), nullable=True),
    sa.Column('os_version', sa.Text(), nullable=True),
    sa.Column('kernel_version', sa.Text(), nullable=True),
    sa.Column('arch', sa.Text(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('total_memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('agent_version', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), server_default=sa.text("'desktop'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('desktop', 'android')", name=op.f('ck_devices_platform')),
    sa.CheckConstraint("status IN ('pending', 'online', 'offline')", name=op.f('ck_devices_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'name', name='uq_devices_user_id_name')
    )
    op.create_index('ix_devices_user_id', 'devices', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.CheckConstraint("revoked_reason IS NULL OR revoked_reason IN ('rotated', 'logout', 'reuse_detected', 'password_change', 'expired', 'admin')", name=op.f('ck_refresh_tokens_revoked_reason')),
    sa.ForeignKeyConstraint(['parent_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_parent_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('agent_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('token_prefix', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_agent_tokens_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_agent_tokens_token_hash'))
    )
    op.create_index('ix_agent_tokens_device_id', 'agent_tokens', ['device_id'], unique=False)
    op.create_index('ix_agent_tokens_user_id', 'agent_tokens', ['user_id'], unique=False)
    op.create_table('enrollment_codes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('code_prefix', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_enrollment_codes_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollment_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_enrollment_codes_code_hash'))
    )
    op.create_index('ix_enrollment_codes_expires_at', 'enrollment_codes', ['expires_at'], unique=False)
    op.create_index('ix_enrollment_codes_user_id', 'enrollment_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security. Second line of defence behind the application's own
    # user_id filtering: one missed WHERE must not leak another user's
    # infrastructure.
    #
    # Enforced only because the app connects as `sentinel_app`, which is
    # NOSUPERUSER + NOBYPASSRLS. A superuser would bypass all of this silently.
    #
    # FORCE ROW LEVEL SECURITY is deliberately NOT used: it would apply these
    # policies to the owner too, so a future data migration doing
    # `UPDATE users SET ...` would quietly affect zero rows. The invariant that
    # the app role is unprivileged is enforced by tests/test_db_role.py instead.
    #
    # With no tenant GUC set, app_current_user_id() returns NULL, the predicate
    # evaluates to NULL, and every row is filtered. The default is deny.
    for table, column in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        # WITH CHECK is not optional: without it an authenticated user could
        # INSERT or UPDATE a row carrying someone else's user_id.
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING ({column} = app_current_user_id())
            WITH CHECK ({column} = app_current_user_id());
            """
        )
    # ### end hand-written RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table, _column in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_codes_user_id', table_name='enrollment_codes')
    op.drop_index('ix_enrollment_codes_expires_at', table_name='enrollment_codes')
    op.drop_table('enrollment_codes')
    op.drop_index('ix_agent_tokens_user_id', table_name='agent_tokens')
    op.drop_index('ix_agent_tokens_device_id', table_name='agent_tokens')
    op.drop_table('agent_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_devices_user_id', table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    # ### end Alembic commands ###
