"""metrics hypertables: system, disk, network, latency and process samples

Table definitions are autogenerated from app/models/metrics.py. Everything
after the autogenerated block is hand-written: TimescaleDB hypertable
conversion, retention policies, and row-level security.

Revision ID: 0004_metrics_hypertables
Revises: 0003_tenant_consistency
Create Date: 2026-08-22 06:56:53.292291+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004_metrics_hypertables'
down_revision: str | Sequence[str] | None = '0003_tenant_consistency'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

from app.models.metrics import CHUNK_INTERVAL, HYPERTABLES, RAW_RETENTION  # noqa: E402


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk_io_samples',
    sa.Column('disk', sa.Text(), nullable=False),
    sa.Column('read_bytes_per_s', sa.Float(), nullable=True),
    sa.Column('write_bytes_per_s', sa.Float(), nullable=True),
    sa.Column('read_iops', sa.Float(), nullable=True),
    sa.Column('write_iops', sa.Float(), nullable=True),
    sa.Column('busy_percent', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_disk_io_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disk', 'device_id', 'ts', name=op.f('pk_disk_io_samples'))
    )
    op.create_index('ix_disk_io_samples_user_id_ts', 'disk_io_samples', ['user_id', 'ts'], unique=False)
    op.create_table('disk_usage_samples',
    sa.Column('mount', sa.Text(), nullable=False),
    sa.Column('filesystem', sa.Text(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_bytes', sa.BigInteger(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_disk_usage_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mount', 'device_id', 'ts', name=op.f('pk_disk_usage_samples'))
    )
    op.create_index('ix_disk_usage_samples_user_id_ts', 'disk_usage_samples', ['user_id', 'ts'], unique=False)
    op.create_table('latency_samples',
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('rtt_ms_avg', sa.Float(), nullable=True),
    sa.Column('rtt_ms_min', sa.Float(), nullable=True),
    sa.Column('rtt_ms_max', sa.Float(), nullable=True),
    sa.Column('packet_loss_percent', sa.Float(), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_latency_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target', 'device_id', 'ts', name=op.f('pk_latency_samples'))
    )
    op.create_index('ix_latency_samples_user_id_ts', 'latency_samples', ['user_id', 'ts'], unique=False)
    op.create_table('metric_samples',
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_percent_min', sa.Float(), nullable=True),
    sa.Column('cpu_percent_max', sa.Float(), nullable=True),
    sa.Column('cpu_user_percent', sa.Float(), nullable=True),
    sa.Column('cpu_system_percent', sa.Float(), nullable=True),
    sa.Column('cpu_iowait_percent', sa.Float(), nullable=True),
    sa.Column('cpu_freq_mhz', sa.Float(), nullable=True),
    sa.Column('ctx_switches_per_s', sa.Float(), nullable=True),
    sa.Column('load1', sa.Float(), nullable=True),
    sa.Column('load5', sa.Float(), nullable=True),
    sa.Column('load15', sa.Float(), nullable=True),
    sa.Column('mem_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mem_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mem_available_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent_min', sa.Float(), nullable=True),
    sa.Column('mem_percent_max', sa.Float(), nullable=True),
    sa.Column('swap_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('swap_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('swap_percent', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('logged_in_users', sa.SmallInteger(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('active_connections', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('fan_rpm', sa.Float(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('battery_plugged', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_metric_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'ts', name=op.f('pk_metric_samples'))
    )
    op.create_index('ix_metric_samples_user_id_ts', 'metric_samples', ['user_id', 'ts'], unique=False)
    op.create_table('net_samples',
    sa.Column('nic', sa.Text(), nullable=False),
    sa.Column('tx_bytes_per_s', sa.Float(), nullable=True),
    sa.Column('rx_bytes_per_s', sa.Float(), nullable=True),
    sa.Column('tx_packets_per_s', sa.Float(), nullable=True),
    sa.Column('rx_packets_per_s', sa.Float(), nullable=True),
    sa.Column('errors_in_per_s', sa.Float(), nullable=True),
    sa.Column('errors_out_per_s', sa.Float(), nullable=True),
    sa.Column('drops_in_per_s', sa.Float(), nullable=True),
    sa.Column('drops_out_per_s', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_net_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nic', 'device_id', 'ts', name=op.f('pk_net_samples'))
    )
    op.create_index('ix_net_samples_user_id_ts', 'net_samples', ['user_id', 'ts'], unique=False)
    op.create_table('process_samples',
    sa.Column('rank_by', sa.Text(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_seconds', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("rank_by IN ('cpu', 'memory')", name=op.f('ck_process_samples_rank_by')),
    sa.ForeignKeyConstraint(['device_id', 'user_id'], ['devices.id', 'devices.user_id'], name='fk_process_samples_device_id_user_id_devices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rank_by', 'rank', 'device_id', 'ts', name=op.f('pk_process_samples'))
    )
    op.create_index('ix_process_samples_user_id_ts', 'process_samples', ['user_id', 'ts'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # TimescaleDB. Converting after create_table (rather than using
    # create_hypertable's own schema definition) keeps the tables in
    # Base.metadata, so autogenerate continues to diff them normally.
    #
    # migrate_data => false: the tables are empty, and TRUE would take a long
    # exclusive lock for no reason.
    for table in HYPERTABLES:
        op.execute(
            f"SELECT create_hypertable('{table}', 'ts', "
            f"chunk_time_interval => INTERVAL '{CHUNK_INTERVAL}', "
            f"migrate_data => false);"
        )
        # Dropping a whole chunk is near-free; a DELETE over 86k rows/device/day
        # would not be. Phase 4 adds the continuous aggregates that outlive this
        # window.
        op.execute(f"SELECT add_retention_policy('{table}', INTERVAL '{RAW_RETENTION}');")

        # Same tenancy model as the rest of the schema: default deny, and
        # WITH CHECK so an authenticated user cannot write rows attributed to
        # another tenant.
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING (user_id = app_current_user_id())
            WITH CHECK (user_id = app_current_user_id());
            """
        )
    # ### end hand-written TimescaleDB + RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in HYPERTABLES:
        # Retention jobs outlive their table unless removed explicitly.
        op.execute(f"SELECT remove_retention_policy('{table}', if_exists => true);")
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_process_samples_user_id_ts', table_name='process_samples')
    op.drop_table('process_samples')
    op.drop_index('ix_net_samples_user_id_ts', table_name='net_samples')
    op.drop_table('net_samples')
    op.drop_index('ix_metric_samples_user_id_ts', table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index('ix_latency_samples_user_id_ts', table_name='latency_samples')
    op.drop_table('latency_samples')
    op.drop_index('ix_disk_usage_samples_user_id_ts', table_name='disk_usage_samples')
    op.drop_table('disk_usage_samples')
    op.drop_index('ix_disk_io_samples_user_id_ts', table_name='disk_io_samples')
    op.drop_table('disk_io_samples')
    # ### end Alembic commands ###
