"""alerts and notifications

Table definitions are autogenerated from app/models/alerts.py and
app/models/notifications.py. The row-level-security block at the end of
upgrade() is hand-written, copying the exact pattern established in
0002_auth_schema.py and 0004_metrics_hypertables.py: default deny, WITH CHECK
so an authenticated user cannot write a row attributed to another tenant, and
no FORCE (which would apply the policy to the owner role too and quietly
break future admin-role data migrations).

Revision ID: 0006_alerts_and_notifications
Revises: 0005_continuous_aggregates
Create Date: 2026-08-22 16:35:18.166763+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_alerts_and_notifications"
down_revision: str | Sequence[str] | None = "0005_continuous_aggregates"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Every table this migration creates that carries a `user_id` column and
#: therefore needs an RLS policy. Order matters for the FK-dependency chain in
#: downgrade()'s drop_table calls below.
TENANT_TABLES = (
    "alert_rules",
    "alert_states",
    "alert_events",
    "alert_silences",
    "notification_settings",
    "web_push_subscriptions",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("email_address", sa.Text(), nullable=True),
        sa.Column(
            "web_push_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "anomaly_sensitivity",
            sa.Text(),
            server_default=sa.text("'medium'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "anomaly_sensitivity IN ('low', 'medium', 'high')",
            name=op.f("ck_notification_settings_anomaly_sensitivity"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_settings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_settings")),
    )
    op.create_table(
        "web_push_subscriptions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_web_push_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_web_push_subscriptions_endpoint")),
    )
    op.create_index(
        "ix_web_push_subscriptions_user_id", "web_push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("comparison", sa.Text(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column(
            "for_duration_seconds", sa.Integer(), server_default=sa.text("60"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("comparison IN ('>', '>=', '<', '<=', '==')", name=op.f("ck_alert_rules_comparison")),
        sa.CheckConstraint(
            "metric IN ('cpu_percent', 'mem_percent', 'swap_percent', 'disk_percent', "
            "'packet_loss_percent', 'cpu_iowait_percent')",
            name=op.f("ck_alert_rules_metric"),
        ),
        sa.CheckConstraint(
            "for_duration_seconds >= 0", name=op.f("ck_alert_rules_for_duration_seconds_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_alert_rules_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_rules_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index("ix_alert_rules_user_id", "alert_rules", ["user_id"], unique=False)
    op.create_table(
        "alert_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("comparison", sa.Text(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'firing'"), nullable=False),
        sa.Column("value_at_fire", sa.Float(), nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_value", sa.Float(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('firing', 'resolved')", name=op.f("ck_alert_events_status")),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_alert_events_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["alert_rules.id"], name=op.f("fk_alert_events_rule_id_alert_rules"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    op.create_index(
        "ix_alert_events_user_id_status_fired_at",
        "alert_events",
        ["user_id", "status", "fired_at"],
        unique=False,
    )
    op.create_table(
        "alert_silences",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("rule_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_alert_silences_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["alert_rules.id"], name=op.f("fk_alert_silences_rule_id_alert_rules"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_silences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_silences")),
    )
    op.create_index("ix_alert_silences_user_id", "alert_silences", ["user_id"], unique=False)
    op.create_table(
        "alert_states",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("pending_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("current_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "last_evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('ok', 'pending', 'firing')", name=op.f("ck_alert_states_state")),
        sa.ForeignKeyConstraint(
            ["current_event_id"],
            ["alert_events.id"],
            name=op.f("fk_alert_states_current_event_id_alert_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_alert_states_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["alert_rules.id"], name=op.f("fk_alert_states_rule_id_alert_rules"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alert_states_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_states")),
        sa.UniqueConstraint("rule_id", "device_id", name="uq_alert_states_rule_id_device_id"),
    )
    op.create_index("ix_alert_states_user_id", "alert_states", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security. Same default-deny pattern as every other tenant
    # table: with no tenant GUC set, app_current_user_id() is NULL and every
    # policy predicate evaluates to NULL, filtering all rows.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING (user_id = app_current_user_id())
            WITH CHECK (user_id = app_current_user_id());
            """
        )
    # ### end hand-written RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alert_states_user_id", table_name="alert_states")
    op.drop_table("alert_states")
    op.drop_index("ix_alert_silences_user_id", table_name="alert_silences")
    op.drop_table("alert_silences")
    op.drop_index("ix_alert_events_user_id_status_fired_at", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index("ix_alert_rules_user_id", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index("ix_web_push_subscriptions_user_id", table_name="web_push_subscriptions")
    op.drop_table("web_push_subscriptions")
    op.drop_table("notification_settings")
    # ### end Alembic commands ###
