"""incidents

Table definitions are autogenerated from app/models/incidents.py. The
`incident_id` column on `alert_events` correlates an event into a device-
level incident — see app/alerts/incident_apply.py. The row-level-security
block at the end of upgrade() is hand-written, copying the exact pattern
established in 0006_alerts_and_notifications.py and every migration since.

Revision ID: 0009_incidents
Revises: 0008_forecast_rules
Create Date: 2026-08-23 00:00:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009_incidents"
down_revision: str | Sequence[str] | None = "0008_forecast_rules"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("incidents",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("summary_model", sa.Text(), nullable=True),
        sa.Column("summary_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_signal_hash", sa.Text(), nullable=True),
        sa.Column("root_cause_text", sa.Text(), nullable=True),
        sa.Column("root_cause_model", sa.Text(), nullable=True),
        sa.Column("root_cause_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("root_cause_signal_hash", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_incidents_status")),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_incidents_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_incidents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(
        "ix_incidents_user_id_status_opened_at",
        "incidents",
        ["user_id", "status", "opened_at"],
        unique=False,
    )
    op.create_index(
        "uq_incidents_one_open_per_device",
        "incidents",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.add_column("alert_events", sa.Column("incident_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_alert_events_incident_id_incidents"),
        "alert_events",
        "incidents",
        ["incident_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security. Same default-deny pattern as every other tenant
    # table: with no tenant GUC set, app_current_user_id() is NULL and every
    # policy predicate evaluates to NULL, filtering all rows.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING (user_id = app_current_user_id())
            WITH CHECK (user_id = app_current_user_id());
            """
        )
    # ### end hand-written RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_alert_events_incident_id_incidents"), "alert_events", type_="foreignkey"
    )
    op.drop_column("alert_events", "incident_id")
    op.drop_index(
        "uq_incidents_one_open_per_device",
        table_name="incidents",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_incidents_user_id_status_opened_at", table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
