"""report schedules

Table definition is autogenerated from app/models/reports.py. The
row-level-security block at the end of upgrade() is hand-written, copying
the exact pattern established in 0006_alerts_and_notifications.py and every
migration since.

Revision ID: 0010_report_schedules
Revises: 0009_incidents
Create Date: 2026-08-23 00:10:16.986538+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0010_report_schedules"
down_revision: str | Sequence[str] | None = "0009_incidents"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("report_schedules",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_schedules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("period_days", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column("cadence", sa.Text(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("format", sa.Text(), server_default=sa.text("'pdf'"), nullable=False),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(cadence = 'weekly' AND day_of_week IS NOT NULL AND day_of_month IS NULL) OR "
            "(cadence = 'monthly' AND day_of_month IS NOT NULL AND day_of_week IS NULL)",
            name=op.f("ck_report_schedules_cadence_fields"),
        ),
        sa.CheckConstraint("cadence IN ('weekly', 'monthly')", name=op.f("ck_report_schedules_cadence")),
        sa.CheckConstraint("format IN ('pdf', 'csv')", name=op.f("ck_report_schedules_format")),
        sa.CheckConstraint(
            "day_of_month IS NULL OR day_of_month BETWEEN 1 AND 28",
            name=op.f("ck_report_schedules_day_of_month_range"),
        ),
        sa.CheckConstraint(
            "day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6",
            name=op.f("ck_report_schedules_day_of_week_range"),
        ),
        sa.CheckConstraint("period_days > 0", name=op.f("ck_report_schedules_period_days_positive")),
        sa.ForeignKeyConstraint(
            ["device_id", "user_id"],
            ["devices.id", "devices.user_id"],
            name="fk_report_schedules_device_id_user_id_devices",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_schedules")),
    )
    op.create_index("ix_report_schedules_user_id", "report_schedules", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security. Same default-deny pattern as every other tenant
    # table: with no tenant GUC set, app_current_user_id() is NULL and every
    # policy predicate evaluates to NULL, filtering all rows.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING (user_id = app_current_user_id())
            WITH CHECK (user_id = app_current_user_id());
            """
        )
    # ### end hand-written RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_report_schedules_user_id", table_name="report_schedules")
    op.drop_table("report_schedules")
    # ### end Alembic commands ###
