"""fcm tokens

Table definition is autogenerated from app/models/notifications.py. The
row-level-security block at the end of upgrade() is hand-written, copying the
exact pattern established in 0006_alerts_and_notifications.py and every
migration since.

Revision ID: 0011_fcm_tokens
Revises: 0010_report_schedules
Create Date: 2026-08-23 06:55:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011_fcm_tokens"
down_revision: str | Sequence[str] | None = "0010_report_schedules"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("fcm_tokens",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fcm_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("device_label", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_fcm_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fcm_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_fcm_tokens_token")),
    )
    op.create_index("ix_fcm_tokens_user_id", "fcm_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security. Same default-deny pattern as every other tenant
    # table: with no tenant GUC set, app_current_user_id() is NULL and every
    # policy predicate evaluates to NULL, filtering all rows.
    #
    # The UNIQUE on `token` is global, not per-tenant, deliberately: an FCM
    # registration token identifies one physical device, and the same phone
    # must not end up addressable by two accounts at once. What happens when a
    # phone already registered to one account registers to another is asserted
    # in tests/test_fcm_registration.py rather than assumed here.
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant ON {table}
            FOR ALL
            USING (user_id = app_current_user_id())
            WITH CHECK (user_id = app_current_user_id());
            """
        )
    # ### end hand-written RLS block ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fcm_tokens_user_id", table_name="fcm_tokens")
    op.drop_table("fcm_tokens")
    # ### end Alembic commands ###
